name = "DPSO Medical"
prefix = "dpsomed"
author = "ArmaForces"
files = [
    "LICENSE",
    "mod.cpp",
    "README.md"
]

exclude = ["*.psd", "*.png", "*.tga"]

modname = "dpso_medical"
keyname = "dpso_medical_{{version}}"
signame = "dpso_medical_{{version}}"

releasebuild = [
]

# HEMTT >= 0.7 (unreleased)
#[header_exts]
#version = "{{git \"id 8\"}}"
# headerexts = [
#     "version={{git \"id 8\"}}"
# ]

# [scripts.Set_version]
#     steps_windows = [
#         "powershell ./tools/Set-Version.ps1 {{version}} '@armaforces_medical'"
#     ]
#     # show_output = true

# [scripts.publish]
#     steps_windows = [
#         "powershell ./tools/Publish.ps1 {{version}} 1981535406 '@armaforces_medical'"
#     ]
#     show_output = true
